call code --install-extension formulahendry.auto-rename-tag
call code --install-extension softwaredotcom.swdc-vscode
call code --install-extension pranaygp.vscode-css-peek
call code --install-extension icrawl.discord-vscode
call code --install-extension dbaeumer.vscode-eslint
call code --install-extension eamodio.gitlens
call code --install-extension VisualStudioExptTeam.vscodeintellicode
call code --install-extension ms-vsliveshare.vsliveshare
call code --install-extension yzhang.markdown-all-in-one
call code --install-extension christian-kohler.npm-intellisense
call code --install-extension zhuangtongfa.material-theme
call code --install-extension esbenp.prettier-vscode
call code --install-extension rvest.vs-code-prettier-eslint
call code --install-extension wayou.vscode-todo-highlight
call code --install-extension vscode-icons-team.vscode-icons
call code --install-extension ritwickdey.LiveServer
call code --install-extension brittanychiang.halcyon-vscode
call code --install-extension pawelgrzybek.gatito-theme
